#!/usr/bin/env npx tsx
/**
 * Parity Verification Script
 *
 * Verifies that every MCP tool has a CLI command equivalent.
 * Run: npx tsx scripts/verify-parity.ts
 *
 * Exit 0 on full parity, exit 1 if gaps exist.
 */

import { allEntityConfigs } from '../packages/core/src/entities/index.js';
import type { CrudEntityConfig } from '../packages/core/src/types/bukku.js';

/**
 * Map entity name to CLI resource subcommand name.
 * Must stay in sync with RESOURCE_NAME_MAP in factory.ts.
 */
const RESOURCE_NAME_MAP: Record<string, string> = {
  'sales-invoice': 'invoices',
  'sales-quote': 'quotes',
  'sales-order': 'orders',
  'sales-credit-note': 'credit-notes',
  'sales-payment': 'payments',
  'sales-refund': 'refunds',
  'delivery-order': 'delivery-orders',
  'purchase-bill': 'bills',
  'purchase-order': 'orders',
  'purchase-credit-note': 'credit-notes',
  'purchase-payment': 'payments',
  'purchase-refund': 'refunds',
  'goods-received-note': 'goods-received-notes',
  'bank-money-in': 'money-in',
  'bank-money-out': 'money-out',
  'bank-transfer': 'transfers',
  'contact': 'contacts',
  'contact-group': 'groups',
  'product': 'products',
  'product-bundle': 'bundles',
  'product-group': 'groups',
  'journal-entry': 'journal-entries',
  'account': 'accounts',
  'file': 'files',
  'location': 'locations',
  'tag': 'tags',
  'tag-group': 'tag-groups',
};

// ---------- Build MCP tool list ----------

const mcpTools: string[] = [];

for (const config of allEntityConfigs) {
  const entity = config.entity;
  for (const op of config.operations) {
    switch (op) {
      case 'list':
        mcpTools.push(`list-${entity}s`);
        break;
      case 'get':
        mcpTools.push(`get-${entity}`);
        break;
      case 'create':
        mcpTools.push(`create-${entity}`);
        break;
      case 'update':
        mcpTools.push(`update-${entity}`);
        break;
      case 'delete':
        mcpTools.push(`delete-${entity}`);
        break;
    }
  }
  if (config.hasStatusUpdate) {
    mcpTools.push(`update-${entity}-status`);
  }
}

// Custom tools not generated by factory
mcpTools.push(
  'upload-file',
  'archive-contact', 'unarchive-contact',
  'archive-product', 'unarchive-product',
  'archive-product-bundle', 'unarchive-product-bundle',
  'search-accounts', 'archive-account', 'unarchive-account',
  'create-journal-entry', 'update-journal-entry',
  'get-location', 'update-location', 'delete-location',
  'archive-location', 'unarchive-location',
  'list-tax-codes', 'list-currencies', 'list-payment-methods',
  'list-terms', 'list-accounts', 'list-price-levels',
  'list-countries', 'list-classification-codes',
  'list-numberings', 'list-states',
);

// ---------- Build CLI command map ----------

/**
 * Generate CLI command string from entity config and operation.
 */
function cliCommand(config: CrudEntityConfig, op: string): string {
  const group = config.cliGroup!;
  const resource = RESOURCE_NAME_MAP[config.entity];
  switch (op) {
    case 'list':
      return `bukku ${group} ${resource} list`;
    case 'get':
      return `bukku ${group} ${resource} get <id>`;
    case 'create':
      return `bukku ${group} ${resource} create`;
    case 'update':
      return `bukku ${group} ${resource} update <id>`;
    case 'delete':
      return `bukku ${group} ${resource} delete <id>`;
    case 'status':
      return `bukku ${group} ${resource} status <id>`;
    default:
      return `bukku ${group} ${resource} ${op}`;
  }
}

const cliCommandMap: Record<string, string> = {};

// Factory-generated mappings
for (const config of allEntityConfigs) {
  if (!config.cliGroup) continue;
  const entity = config.entity;
  for (const op of config.operations) {
    const toolName = op === 'list' ? `list-${entity}s`
      : `${op}-${entity}`;
    cliCommandMap[toolName] = cliCommand(config, op);
  }
  if (config.hasStatusUpdate) {
    cliCommandMap[`update-${entity}-status`] = cliCommand(config, 'status');
  }
}

// Custom tool mappings
cliCommandMap['upload-file'] = 'bukku files upload <path>';
cliCommandMap['archive-contact'] = 'bukku contacts contacts archive <id>';
cliCommandMap['unarchive-contact'] = 'bukku contacts contacts unarchive <id>';
cliCommandMap['archive-product'] = 'bukku products products archive <id>';
cliCommandMap['unarchive-product'] = 'bukku products products unarchive <id>';
cliCommandMap['archive-product-bundle'] = 'bukku products bundles archive <id>';
cliCommandMap['unarchive-product-bundle'] = 'bukku products bundles unarchive <id>';
cliCommandMap['search-accounts'] = 'bukku accounting search-accounts';
cliCommandMap['archive-account'] = 'bukku accounting accounts archive <id>';
cliCommandMap['unarchive-account'] = 'bukku accounting accounts unarchive <id>';
cliCommandMap['create-journal-entry'] = 'bukku accounting journal-entries create';
cliCommandMap['update-journal-entry'] = 'bukku accounting journal-entries update <id>';
cliCommandMap['get-location'] = 'bukku control-panel locations get <id>';
cliCommandMap['update-location'] = 'bukku control-panel locations update <id>';
cliCommandMap['delete-location'] = 'bukku control-panel locations delete <id>';
cliCommandMap['archive-location'] = 'bukku control-panel locations archive <id>';
cliCommandMap['unarchive-location'] = 'bukku control-panel locations unarchive <id>';
cliCommandMap['list-tax-codes'] = 'bukku ref-data tax-codes';
cliCommandMap['list-currencies'] = 'bukku ref-data currencies';
cliCommandMap['list-payment-methods'] = 'bukku ref-data payment-methods';
cliCommandMap['list-terms'] = 'bukku ref-data terms';
cliCommandMap['list-accounts'] = 'bukku ref-data accounts';
cliCommandMap['list-price-levels'] = 'bukku ref-data price-levels';
cliCommandMap['list-countries'] = 'bukku ref-data countries';
cliCommandMap['list-classification-codes'] = 'bukku ref-data classification-codes';
cliCommandMap['list-numberings'] = 'bukku ref-data numberings';
cliCommandMap['list-states'] = 'bukku ref-data states';

// ---------- Compare ----------

const missing: string[] = [];
for (const tool of mcpTools) {
  if (!cliCommandMap[tool]) {
    missing.push(tool);
  }
}

console.log(`MCP Tools: ${mcpTools.length}`);
console.log(`CLI Commands: ${Object.keys(cliCommandMap).length}`);
console.log(`Coverage: ${Math.round(((mcpTools.length - missing.length) / mcpTools.length) * 100)}%`);
console.log('');

if (missing.length > 0) {
  console.log('Missing CLI commands:');
  for (const tool of missing) {
    console.log(`  - ${tool}`);
  }
  process.exit(1);
} else {
  console.log('Missing CLI commands: (none)');
  console.log('');
  console.log('All MCP tools have CLI command equivalents.');
}
